---
- name: Install Minishift.
  hosts: Pisc0
  connection: local
  gather_facts: yes
  vars:
    vm: openshift0

  roles:
    #- role: chilcano.minishift
    - role: ../ansible-role-minishift
      minishift:
        action_to_trigger: install # [ install | fresh_install | clean ]
        action:
          clean:
            installation: true
            local_repo: false
            local_tmp: false
            dependencies: false
        post_copy_oc: false
        start_options:
          vm-driver: virtualbox
          #iso-url: file:///Users/Chilcano/Downloads/__kube_repo/minishift-b2d-iso/v1.2.0/minishift-b2d.iso
          #iso-url: file:///Users/Chilcano/Downloads/__kube_repo/minishift-centos-iso/v1.2.0/minishift-centos7.iso
          iso-url: https://github.com/minishift/minishift-b2d-iso/releases/download/v1.2.0/minishift-b2d.iso
          #iso-url: https://github.com/minishift/minishift-centos-iso/releases/download/v1.2.0/minishift-centos7.iso
          profile: "{{ vm }}"
          #openshift-version: ""        # latest (https://hub.docker.com/r/openshift/origin/tags)
          openshift-version: "v3.7.0"
          #openshift-version: "v3.6.0"
          #openshift-version: "v1.5.1"  # v3.5.1
          #openshift-version: "v1.5.0"  # v3.5.0
          show-libmachine-logs: ""
        openshift:
          admin_usr: "system:admin"
          admin_pwd: anypassword
        repo:
          name: minishift/minishift
          release_tag_name: "" # latest
          #release_tag_name: "v1.8.0"
          #release_tag_name: "v1.7.0"
          #release_tag_name: "v1.6.0"
