- name: clean | Remove current Minishift instance
  include: clean_minishift.yml
  when: __ms.action.clean.installation and minishift_cli.stat.exists

- name: clean | Remove 'local_repo' dir (you will need to download tarballs, etc.)
  file:
    path: "{{ __ms.dir.local_repo }}"
    state: absent
  when: __ms.action.clean.local_repo

- name: clean | Remove local_tmp dir
  file:
    path: "{{ __ms.dir.local_tmp }}"
    state: absent
  when: __ms.action.clean.local_tmp

- name: clean | Remove installed Docker machine driver
  include: "clean_driver_{{ ansible_os_family }}.yml"
  when: __ms.action.clean.dependencies

- name: clean | Remove Minishift hostname from '/etc/hosts' file
  include: clean_hostname_from_hosts_file.yml
