- name: clean_minishift | Debug '__ms.start_options.profile'
  debug:
    var: __ms.start_options.profile

- name: clean_minishift | Debug 'instance_status'
  debug:
    var: instance_status

- name: clean_minishift | Debug 'instance_ip_address'
  debug:
    var: instance_ip_address

### requires '$ pip install pexpect' (on host that executes module)
### set mac osx' hostname:
# $ scutil --set ComputerName yourhostname
# $ scutil --set LocalHostName yourhostname
# $ scutil --set HostName yourhostname
# $ scutil --get HostName
- name: clean_minishift | Delete Minishift 'profile {{ __ms.start_options.profile }} / IP {{ instance_ip_address }}' and port '8443'
  expect:
    command: "minishift profile delete {{ __ms.start_options.profile }}"
    responses:
      "You are deleting the active profile. It will remove the VM and all related artifacts. Do you want to continue": "y"
      "Will remove the VM and all the related artifacts. Do you want to continue": "y"
    #timeout: 60
    echo: yes
  ### It removes the VM when status='Does Not Exist' or 'action_to_trigger' is 'clean'. If VM is 'Running', then VM will be stopped and reuse it.
  ### If 'action_to_trigger' is 'fresh_install', then the VM will be stopped and reuse it.
  when: instance_status.stdout | regex_search('Does Not Exist') or __ms.action_to_trigger == 'clean'
  delegate_to: 127.0.0.1

- name: clean_minishift | Remove Kubernetes cache for '{{ __ms.start_options.profile }} / {{ instance_ip_address }}' and port '8443'
  file:
    path: "~/.kube/{{ instance_ip_address }}_8443"
    state: absent
