- name: clean_hostname_from_hosts_file | Remove hostname '{{ __ms.start_options['profile'] }}'
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ __ms.start_options['profile'] }}"
    state: absent
  become: yes
