# examples of iso-url:
#   https://github.com/minishift/minishift-b2d-iso/releases/download/v1.1.0/minishift-b2d.iso
#   https://github.com/minishift/minishift-centos-iso/releases/download/v1.1.0/minishift-centos7.iso
- name: install | get_docker_iso | Getting Docker Machine iso filename, type and version
  set_fact:
    docker_iso_filename: "{{ __ms.start_options['iso-url'] | basename }}"
    docker_iso_filename_without_ext: "{{ __ms.start_options['iso-url'] | basename | regex_replace('^(.+).iso$', '\\1') }}"
    docker_iso_type: "{{ __ms.start_options['iso-url'] | regex_replace('^https://github.com/minishift/(.+)/releases/download/(.+)/.+$', '\\1') }}"
    docker_iso_version: "{{ __ms.start_options['iso-url'] | regex_replace('^https://github.com/minishift/(.+)/releases/download/(.+)/.+$', '\\2') }}"

- name: install | get_docker_iso | Create the directory to allocate the downloaded file
  file:
    path: "{{ __ms.dir.local_repo }}/{{ docker_iso_type }}/{{ docker_iso_version }}"
    state: directory
    recurse: yes

- name: install | get_docker_iso | Check if Docker Machine iso file exists in local
  stat:
    path: "{{ __ms.dir.local_repo }}/{{ docker_iso_type }}/{{ docker_iso_version }}/{{ docker_iso_filename }}"
  register: docker_iso_file_path_stat

- name: install | get_docker_iso | Check if Docker Machine URL is working
  uri:
    url: "{{ __ms.start_options['iso-url'] }}"
    method: HEAD
  register: docker_iso_url_test
  failed_when: docker_iso_url_test.status is undefined or docker_iso_url_test.status <= 0
  when: not docker_iso_file_path_stat.stat.exists

- name: install | get_docker_iso | Gracefully ends playbook if http code is fatal
  meta: end_play
  when: not docker_iso_file_path_stat.stat.exists and docker_iso_url_test.status > 400

- name: install | get_docker_iso | Download Docker Machine ISO from '{{ __ms.start_options["iso-url"] }}'
  get_url:
    url: "{{ __ms.start_options['iso-url'] }}"
    dest: "{{ __ms.dir.local_repo }}/{{ docker_iso_type }}/{{ docker_iso_version }}"
  when: not docker_iso_file_path_stat.stat.exists

- name: install | get_docker_iso | Create a new fact for 'minishift.start_options["iso-url"]' value
  set_fact:
    _new_docker_iso_url_: "file://{{ __ms.dir.local_repo }}/{{ docker_iso_type }}/{{ docker_iso_version }}/{{ docker_iso_filename }}"

- name: install | get_docker_iso | Update global dict with new 'minishift.start_options["iso-url"]' value
  set_fact:
     __ms: "{{ __ms | combine( {'start_options':{'iso-url':_new_docker_iso_url_}}, recursive=True ) }}"
