- name: install_update_hosts_file | Updating '/etc/hosts'
  lineinfile:
    dest: /etc/hosts
    line: '{{ item }}'
  with_items:
    - "{{ instance_ip_address }} {{ __ms.start_options['profile'] }}"
    - "{{ instance_ip_address }} hawkular-metrics-openshift-infra.{{ instance_ip_address }}.nip.io"  # --metrics enabled
    - "{{ instance_ip_address }} kibana-logging.{{ instance_ip_address }}.nip.io"  # --logging enabled
  become: yes
