- name: install_update_hosts_file | Remove hostname '{{ __ms.start_options['profile'] }}'
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ __ms.start_options['profile'] }}"
    state: absent
  become: yes

- name: install_update_hosts_file | Updating '/etc/hosts' with '{{ instance_ip_address }} {{ __ms.start_options['profile'] }}'
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{ instance_ip_address }}'
    line: "{{ instance_ip_address }}  {{ __ms.start_options['profile'] }}"
  become: yes
