- name: install | Check if docker-machine-driver-xhyve is installed
  command: brew info --installed docker-machine-driver-xhyve
  register: output

- name: install | Install docker-machine-driver-xhyve
  homebrew:
    name: install | docker-machine-driver-xhyve
    state: present
  when: "'Not installed' in output.stdout"

- name: install | Get brew prefix
  command: brew --prefix
  register: prefix

- name: install | Set owner for docker-machine-driver-xyhve
  command: "chown root:wheel {{ prefix.stdout }}/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve"
  become: yes
  when: "'Not installed' in output.stdout"

- name: install | Set permissions for docker-machine-driver-xhyve
  command: "chmod u+s {{ prefix.stdout }}/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve"
  become: yes
  when: "'Not installed' in output.stdout"
