- name: install | Debug '__ms.start_options.profile'
  debug:
    var: __ms.start_options.profile

- name: install | Debug 'instance_status'
  debug:
    var: instance_status

- name: install | Debug 'instance_ip_address'
  debug:
    var: instance_ip_address

- name: install | Include YML to install Docker machine driver
  include: "install_driver_{{ ansible_os_family }}.yml"

- name: install | Include YML to download Docker Machine for Minishift
  include: "get_docker_iso.yml"
  when: __ms.start_options['iso-url'] | regex_search('^https?://.+')

- name: install | Include YML to download Minishift bundles
  include: "get_minishift.yml"

- name: install | Start Minishift
  include: install_start_minishift.yml
  when: __ms.action.start

- name: install | Update '/etc/hosts' file
  include: install_update_hosts_file.yml
