- name: set_oc | Check if 'oc' binary exists in PATH
  stat:
    path: "{{ __ms.dir.local_bin }}/oc"
  register: oc_current_client

- name: set_oc | Get the path to the 'oc' client for Minishift '{{ __ms.start_options.profile }}' instance
  find:
    #paths: "{{ lookup('env', 'HOME') }}/.minishift/profiles/{{ __ms.start_options.profile }}/cache/oc"   ## for < v3.7
    paths: "{{ lookup('env', 'HOME') }}/.minishift/cache/oc/"                                             ## for >= v3.7
    patterns: "{{ ansible_os_family | lower }}"
    recurse: yes
    hidden: yes
    file_type: directory
  register: oc_versions

- name: set_oc | Initializing 'my_oc' fact
  set_fact:
    my_oc: "{{ __ms.dir.local_bin }}/oc"

- name: set_ | Set 'my_oc' with last value of 'oc_versions.files'
  set_fact:
    my_oc: "{{ (oc_versions.files | last).path }}/oc"
  when: oc_versions.files | length == 1 and not oc_current_client.stat.exists and not __ms.post_copy_oc

- name: set_ | Copy or overwrite 'oc' client in PATH
  copy:
    src: "{{ (oc_versions.files | last).path }}/oc"
    dest: "{{ __ms.dir.local_bin }}/oc"
    mode: 0755
    remote_src: yes
  become: yes
  when: oc_versions.files | length == 1 and __ms.post_copy_oc
